/* This file is generated by scripts/generate-format-catalog.mjs. Do not edit directly. */
import type { RendererDefinition } from '../contracts/types';

export const DEFAULT_RENDERER_DEFINITIONS = [
  {
    "id": "office-word-openxml",
    "label": "Word OpenXML",
    "category": "office",
    "extensions": [
      "docx",
      "docm",
      "dotx",
      "dotm"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML Transitional",
      "OOXML Strict"
    ],
    "knownLimits": [
      "VBA is never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-word-binary",
    "label": "Word Binary",
    "category": "office",
    "extensions": [
      "doc",
      "dot"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "Word 97-2003 Binary"
    ],
    "knownLimits": [
      "Macros are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-presentation-binary",
    "label": "PowerPoint 97–2003",
    "category": "office",
    "extensions": [
      "ppt",
      "pot"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-ppt",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "PowerPoint 97-2003 Binary"
    ],
    "knownLimits": [
      "Embedded engine watermark is retained",
      "Macros are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "office-presentation",
    "label": "PowerPoint OpenXML",
    "category": "office",
    "extensions": [
      "pptx",
      "pptm",
      "potx",
      "potm",
      "ppsx",
      "ppsm"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-pptx",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML Transitional",
      "OOXML Strict"
    ],
    "knownLimits": [
      "Macros and external programs are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "open-document",
    "label": "Open Document",
    "category": "office",
    "extensions": [
      "rtf",
      "odt",
      "odp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "RTF",
      "OpenDocument"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "spreadsheet-openxml",
    "label": "Spreadsheet",
    "category": "office",
    "extensions": [
      "xlsx",
      "xltx",
      "xlsm",
      "xlsb",
      "xls",
      "xlt",
      "xla",
      "xlam",
      "xltm",
      "csv",
      "tsv",
      "ods",
      "fods"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-spreadsheet",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML",
      "BIFF",
      "OpenDocument",
      "Delimited text"
    ],
    "knownLimits": [
      "VBA and add-in code are never executed",
      "Formula results are read from the saved workbook cache"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-pages",
    "label": "Apple Pages",
    "category": "office",
    "extensions": [
      "pages"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.xml(.gz)",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Static preview only",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-numbers",
    "label": "Apple Numbers",
    "category": "office",
    "extensions": [
      "numbers"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.xml",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Formula results are read from the saved document cache",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-keynote",
    "label": "Apple Keynote",
    "category": "office",
    "extensions": [
      "key"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.apxl",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Animations, transitions and video playback are not executed",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-wordperfect",
    "label": "WordPerfect",
    "category": "office",
    "extensions": [
      "wpd",
      "wp",
      "wp5",
      "wp6"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-wordperfect",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "WordPerfect 4.2",
      "WordPerfect 5.x",
      "WordPerfect 6+"
    ],
    "knownLimits": [
      "Macros are never executed",
      ".wp5 and .wp6 are routing aliases for genuine WP5/WP6 payloads, not separate container formats",
      "Pagination and unsupported embedded objects are presented as structured static preview"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "spreadsheet-dbf",
    "label": "dBASE Table",
    "category": "office",
    "extensions": [
      "dbf"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-spreadsheet",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "dBASE III/IV",
      "Visual FoxPro"
    ],
    "knownLimits": [
      "Missing DBT/FPT memo sidecars are reported as incomplete"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "pdf",
    "label": "PDF",
    "category": "document",
    "extensions": [
      "pdf"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-pdf",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "PDF"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": "provider"
    }
  },
  {
    "id": "ofd",
    "label": "OFD",
    "category": "document",
    "extensions": [
      "ofd"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-ofd",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OFD"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-hangul",
    "label": "Hancom Hangul",
    "category": "office",
    "extensions": [
      "hwp",
      "hwpx"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-hangul",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "HWP v5 CFB",
      "HWPX ZIP/XML"
    ],
    "knownLimits": [
      "Encrypted, DRM-protected and distribution documents are detected but not decrypted",
      "Charts, OLE objects and advanced drawing effects remain limited in the static structured preview",
      "HWP v5 pagination is approximated when the binary producer omits usable page geometry"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "typst",
    "label": "Typst",
    "category": "document",
    "extensions": [
      "typ",
      "typst"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-typst",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Typst source"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "archive",
    "label": "Archive",
    "category": "archive",
    "extensions": [
      "zip",
      "zipx",
      "7z",
      "rar",
      "tar",
      "gz",
      "gzip",
      "tgz",
      "bz2",
      "bzip2",
      "tbz",
      "tbz2",
      "xz",
      "txz",
      "lzma",
      "zst",
      "tzst",
      "cab",
      "ar",
      "cpio",
      "iso",
      "xar",
      "lha",
      "lzh",
      "jar",
      "war",
      "ear",
      "apk",
      "cbz",
      "cbr"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-archive",
    "presets": [
      "standard",
      "all"
    ],
    "containerVersions": [
      "libarchive-supported containers"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "chm",
    "label": "Compiled HTML Help",
    "category": "ebook",
    "extensions": [
      "chm"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-chm",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Microsoft HTML Help ITSF v2/v3",
      "LZX MSCompressed and uncompressed content"
    ],
    "knownLimits": [
      "ActiveX, Shortcut/WinHelp commands, scripts and external network resources are intentionally blocked",
      "Merged help collections require each referenced CHM file to be opened separately"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "email",
    "label": "Email",
    "category": "email",
    "extensions": [
      "eml",
      "msg",
      "mbox"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-email",
    "presets": [
      "standard",
      "all"
    ],
    "containerVersions": [
      "MIME",
      "Outlook MSG",
      "mbox"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "eda",
    "label": "EDA",
    "category": "eda",
    "extensions": [
      "olb",
      "dra",
      "gds",
      "oas",
      "oasis"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-eda",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "OrCAD",
      "GDSII",
      "OASIS"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "cad",
    "label": "CAD",
    "category": "cad",
    "extensions": [
      "dxf",
      "dwg",
      "dwf",
      "dwfx",
      "xps"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-cad",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "DWG",
      "DXF",
      "DWF",
      "DWFX/XPS"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "model",
    "label": "3D Model",
    "category": "model",
    "extensions": [
      "glb",
      "gltf",
      "obj",
      "stl",
      "ply",
      "fbx",
      "dae",
      "3ds",
      "3mf",
      "amf",
      "usd",
      "usda",
      "usdc",
      "usdz",
      "kmz",
      "step",
      "stp",
      "iges",
      "igs",
      "ifc",
      "3dm",
      "brep",
      "pcd",
      "wrl",
      "vrml",
      "xyz",
      "vtk",
      "vtp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-3d",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "Mesh",
      "CAD exchange",
      "scene"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "geo",
    "label": "Geospatial",
    "category": "geo",
    "extensions": [
      "geojson",
      "kml",
      "gpx",
      "shp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-geo",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "GeoJSON",
      "KML",
      "GPX",
      "Shapefile"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "drawing",
    "label": "Drawing",
    "category": "drawing",
    "extensions": [
      "excalidraw",
      "drawio",
      "dio",
      "mermaid",
      "mmd",
      "plantuml",
      "puml"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-drawing",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Draw.io",
      "Excalidraw",
      "Mermaid",
      "PlantUML"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "bpmn",
    "label": "BPMN 2.0",
    "category": "drawing",
    "extensions": [
      "bpmn"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-drawing",
    "presets": [],
    "containerVersions": [
      "BPMN 2.0 XML with BPMN DI"
    ],
    "knownLimits": [
      "Explicit opt-in with bpmn-js",
      "Diagram preview requires BPMN DI layout; source remains available without it",
      "Read-only preview; process scripts are never executed",
      "The bpmn.io watermark is retained under the upstream license"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "mindmap",
    "label": "Mind Map",
    "category": "mindmap",
    "extensions": [
      "xmind"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-mindmap",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "XMind"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "str",
    "label": "STR Bundle",
    "category": "structured-data",
    "extensions": [
      "str"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-str",
    "presets": [],
    "containerVersions": [
      "STR 1.x bundle directory"
    ],
    "knownLimits": [
      "Explicit opt-in: `@file-viewer/renderer-str` is not part of any preset or full-package closure; install it and pass `strRenderer` through `options.renderers` (or `renderers`)",
      "A .str bundle is a directory: the viewer needs FileViewerSource.files (folder picker or directory drag-and-drop) or options.str.files because a single File cannot carry a bundle",
      "The structure tree is parsed from the .str.toml manifests; manifest drift is reported instead of repaired",
      "A `<bundle>.str.zip` name - how macOS delivers a bundle package to a file input - routes here and is unpacked in memory; a plain `.zip` still belongs to the archive renderer",
      "Bundle archives are read from stored and deflate members; ZIP64, encrypted archives, unknown compression methods and any single member above 1 GiB are rejected with the reason instead of being mis-parsed",
      "Opening a `.str.zip` only walks the member directory and inflates the `.str.toml` manifests; payload bytes stay compressed until a file is previewed or downloaded, so a bundle holding hundreds of megabytes still renders its structure tree",
      "Soft links expand the target branch and hard links show the target content read-only; editing, creating and validating bundles is out of scope"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "epub",
    "label": "EPUB",
    "category": "ebook",
    "extensions": [
      "epub"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "EPUB 2",
      "EPUB 3"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": "provider"
    }
  },
  {
    "id": "ebook-fb2",
    "label": "FictionBook",
    "category": "ebook",
    "extensions": [
      "fb2"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "FictionBook 2 XML"
    ],
    "knownLimits": [
      "External network resources are not loaded"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "umd",
    "label": "UMD",
    "category": "ebook",
    "extensions": [
      "umd"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "UMD"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "image",
    "label": "Image",
    "category": "image",
    "extensions": [
      "gif",
      "jpg",
      "jpeg",
      "bmp",
      "tiff",
      "tif",
      "png",
      "svg",
      "webp",
      "avif",
      "ico",
      "heic",
      "heif",
      "jxl"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-image",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Raster",
      "SVG"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "dicom",
    "label": "DICOM",
    "category": "medical-image",
    "extensions": [
      "dcm",
      "dicom"
    ],
    "async": true,
    "supportLevel": "basic",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-dicom",
    "presets": [],
    "containerVersions": [
      "DICOM Part 10"
    ],
    "knownLimits": [
      "Local single-file and multi-frame viewing only; series assembly, PACS/DICOMweb, MPR, segmentation, measurement tools, and diagnostic-use claims are not included",
      "Tested transfer syntaxes are Implicit/Explicit VR Little Endian, JPEG Lossless Process 14 SV1, JPEG-LS Lossless, and JPEG 2000 Lossless"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "signature",
    "label": "Digital signatures and evidence containers",
    "category": "cryptographic-container",
    "extensions": [
      "p7m",
      "p7s",
      "p7c",
      "p7b",
      "pkcs7",
      "cms",
      "cmsc",
      "tsd",
      "tst",
      "tsq",
      "tsr",
      "asics",
      "scs",
      "asice",
      "sce",
      "ers",
      "asc",
      "sig",
      "pgp",
      "gpg",
      "jws"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-signature",
    "presets": [],
    "containerVersions": [
      "CMS/PKCS#7",
      "CAdES attributes",
      "RFC 3161",
      "RFC 5544",
      "ASiC-S/E",
      "RFC 4998",
      "RFC 7515",
      "OpenPGP RFC 9580"
    ],
    "knownLimits": [
      "Opt-in renderer; it is not added to the published preset-all/full compatibility closure",
      "Cryptographic checks are reported separately from certificate/key trust, policy, qualified-signature status and legal validity",
      "ASiC XML references and RFC 4998 renewal chains are structurally inspected; full XAdES and archival-policy validation are not claimed",
      "OpenPGP private-key operations and automatic decryption are intentionally excluded"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "markdown",
    "label": "Markdown",
    "category": "markdown",
    "extensions": [
      "md",
      "markdown"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-text",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "CommonMark/GFM"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "code",
    "label": "Code and Text",
    "category": "code",
    "extensions": [
      "txt",
      "json",
      "js",
      "mjs",
      "cjs",
      "css",
      "java",
      "py",
      "html",
      "htm",
      "jsx",
      "ts",
      "tsx",
      "xml",
      "log",
      "vue",
      "yaml",
      "yml",
      "ini",
      "sh",
      "bash",
      "sql",
      "go",
      "rs",
      "php",
      "c",
      "cpp",
      "cc",
      "h",
      "hpp",
      "cs",
      "diff",
      "patch",
      "bundle",
      "bdl",
      "jsonc",
      "json5",
      "ipynb",
      "toml",
      "proto",
      "hcl",
      "tex",
      "gv",
      "http",
      "react",
      "rb",
      "swift",
      "kt"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-text",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Plain text",
      "source code",
      "Git bundle"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "video",
    "label": "Video",
    "category": "media",
    "extensions": [
      "mp4",
      "webm",
      "m3u8"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-media",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Browser media"
    ],
    "knownLimits": [
      "Codec support follows the browser"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "audio",
    "label": "Audio",
    "category": "media",
    "extensions": [
      "mp3",
      "mpeg",
      "wav",
      "ogg",
      "oga",
      "opus",
      "m4a",
      "aac",
      "flac",
      "weba",
      "midi",
      "mid"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-media",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Browser media",
      "MIDI"
    ],
    "knownLimits": [
      "Codec support follows the browser"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "photoshop-design",
    "label": "Adobe Photoshop",
    "category": "asset",
    "extensions": [
      "psb",
      "pdd",
      "psdt"
    ],
    "async": true,
    "supportLevel": "experimental",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "enhancesRendererId": "data-asset",
    "enhancesExtensions": [
      "psd"
    ],
    "containerVersions": [
      "PSD v1",
      "PSB v2"
    ],
    "knownLimits": [
      "Pixel rendering is enabled only for 8-bit RGB and grayscale documents; unsupported color modes and bit depths are rejected instead of decoded incorrectly",
      "The untouched merged composite is the fidelity reference and must have been saved with Maximize Compatibility using Raw or PackBits RLE compression; ZIP composites are rejected",
      "Auxiliary channels are accepted only when PSD layer-info declares one merged-transparency channel; PSB currently requires exactly the base RGB or grayscale channels",
      "Embedded ICC profiles are detected but not color-converted yet, so profiled color is not reference-verified",
      "The PSD/PSB container version is taken from the 8BPS header; a mismatched filename extension is diagnosed and never used as the format authority",
      "Legacy PhotoDeluxe PDD and Photoshop template PSDT inputs are accepted only when the bytes validate as a PSD v1 8BPS container; unrelated files sharing those extensions are rejected",
      "PSD layer visibility is interactive only for flat normal-blend 100%-opacity documents without masks, effects, clipping, adjustments, groups, or resource-limit violations",
      "PSB currently exposes the saved composite and a read-only layer tree; interactive PSB layer recomposition is not claimed, and PSB files containing ZIP-compressed layer channels are rejected"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": false,
      "zoom": true,
      "search": false
    }
  },
  {
    "id": "illustrator-pdf-design",
    "label": "Adobe Illustrator AI/AIT",
    "category": "asset",
    "extensions": [
      "ait"
    ],
    "async": true,
    "supportLevel": "experimental",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "enhancesRendererId": "data-asset",
    "enhancesExtensions": [
      "ai"
    ],
    "containerVersions": [
      "Illustrator PDF-compatible AI/AIT",
      "Illustrator native PGF/private source"
    ],
    "knownLimits": [
      "Automatic mode prefers the verified PDF-compatible surface for the highest saved appearance fidelity, while Native PGF mode parses the editable private source in a dedicated bounded Worker and exposes native artboards and layer visibility",
      "A PDF header alone is insufficient: the renderer also requires Illustrator-origin XMP, MIME, creator, or AIPrivateData evidence so an ordinary renamed PDF is not advertised as an Illustrator document",
      "The packaged browser Worker decodes uncompressed, deflate, and Illustrator 24 zstd private source entirely offline; zstd output is streamed through the same decoded-byte ceiling and unsupported long-distance frames fail explicitly",
      "Native PGF rendering currently preserves and reports unknown operators but does not claim complete Illustrator gradients, text shaping, placed or embedded images, plugins, effects, masks, blending, overprint, spot-color management, or font substitution fidelity",
      "The PDF renderer is required only for the saved PDF surface; native-only AI/AIT can open without it, and PDF pages or optional-content groups are not presented as native artboards or layers"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": false,
      "zoom": true,
      "search": true
    }
  },
  {
    "id": "indesign-idml-design",
    "label": "Adobe InDesign IDML",
    "category": "asset",
    "extensions": [
      "idml"
    ],
    "async": true,
    "supportLevel": "experimental",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "IDML package",
      "@paged-media/introspect-wasm 0.63.0"
    ],
    "knownLimits": [
      "Pages are rendered locally by the CPU WASM engine in a module Worker; the browser never uploads the IDML package",
      "ZIP64, encrypted, multi-disk, overlapping, unsafe-path, unsupported-compression, and configured expansion-limit packages are rejected before the WASM engine opens them",
      "The current engine page tree lists TextFrame and Rectangle objects only even though other supported objects may still appear in rendered page pixels",
      "Each page render rebuilds the upstream document internally; interactive requests are latest-wins, preview is lazy, and print-all is bounded by the configured total RGBA working-set limit"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": false,
      "zoom": true,
      "search": false
    }
  },
  {
    "id": "indesign-exchange-design",
    "label": "Adobe InCopy and InDesign Exchange",
    "category": "asset",
    "extensions": [
      "icml",
      "idms",
      "inx"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "ICML InCopyInterchange",
      "IDMS PageItem",
      "legacy INX"
    ],
    "knownLimits": [
      "ICML is rendered as styled story content because the format does not carry a complete document page layout",
      "IDMS page-item paths, transforms, colors, stories, styles, layers, and linked-resource metadata are parsed in a terminable Worker and shown as a bounded layout-fragment preview; it is not advertised as a complete INDD page",
      "Legacy INX abbreviated records have no maintained browser layout engine; common page items and geometry are visualized while every unmapped element name remains visible in the structure inventory",
      "UTF-8, signature, DTD/entity, source size, node, depth, attribute, text, story, item, point, style, and color limits are enforced; linked resource paths are never fetched"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "adobe-animate-xfl-design",
    "label": "Adobe Animate XFL",
    "category": "asset",
    "extensions": [
      "fla",
      "xfl"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "Modern compressed XFL-based FLA (CS5+)",
      "single DOMDocument XML XFL"
    ],
    "knownLimits": [
      "Modern ZIP/XFL-based FLA is parsed in a terminable Worker; legacy binary FLA (Flash CS4 and earlier) is explicitly rejected",
      "The bounded first-frame preview reconstructs solid shapes, static text, nested symbols, and direct PNG/JPEG instances; masks, filters, tweens, ActionScript, audio/video playback, and proprietary bitmap .dat payloads remain structure-only",
      "A standard uncompressed .xfl is only a marker beside DOMDocument.xml, LIBRARY, and media folders; a single browser File object cannot access those siblings, so it must be packaged as FLA or supplied through a future folder/multi-file API",
      "ZIP64, encryption, multi-disk archives, overlapping records, unsafe or ambiguous paths, CRC failures, unsupported compression, DTD/entity XML, external XML stylesheets, and configured size/node/depth/ratio limits are rejected"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "adobe-xd-design",
    "label": "Adobe XD Package",
    "category": "asset",
    "extensions": [
      "xd"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "XD UCF package",
      "AGC JSON inventory"
    ],
    "knownLimits": [
      "A terminable module Worker shows the highest-resolution structurally referenced embedded PNG/JPEG rendition and a bounded manifest, artboard, layer, and resource inventory",
      "Native AGC vector scene reconstruction is not implemented; files without a saved preview remain structure-only",
      "ZIP64, encrypted, multi-disk, overlapping, unsafe-path, CRC-invalid, unsupported-compression, and configured expansion-limit packages are rejected"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "indesign-native-design",
    "label": "Adobe InDesign Native",
    "category": "asset",
    "extensions": [
      "indd",
      "indt"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "InDesign 2+ native database",
      "INDD",
      "INDT"
    ],
    "knownLimits": [
      "A terminable module Worker shows a JPEG/PNG preview only when it is embedded in a structurally verified contiguous XMP object",
      "The proprietary native layout database is not reconstructed; files without a saved XMP thumbnail remain metadata- or structure-only and should be exported to IDML for full page rendering",
      "The reader follows declared master-page and object boundaries and never scans arbitrary binary bytes for coincidental image signatures; legacy InDesign 1.x is rejected"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "postscript-design",
    "label": "Adobe EPS and PostScript",
    "category": "asset",
    "extensions": [
      "ps"
    ],
    "async": true,
    "supportLevel": "experimental",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "enhancesRendererId": "data-asset",
    "enhancesExtensions": [
      "eps"
    ],
    "containerVersions": [
      "EPSF/DSC PostScript",
      "Adobe PostScript programs"
    ],
    "knownLimits": [
      "Stet WASM renders pages in a terminable Worker with latest-wins interactive requests and bounded source size, VM memory, page count, dimensions, pixels, DPI, total print working set, and retained canvas cache",
      "The distributed runtime excludes upstream URW Base35 and Ghostscript CMYK ICC assets; Carlito, Tinos, Cousine, and Noto Sans Symbols 2 OFL substitutes plus the PLRM DeviceCMYK formula fallback can differ in metrics and color from Adobe applications",
      "This experimental path is not claimed to implement every Adobe PostScript Level 3 operator, font technology, color-management workflow, or printer device"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": false,
      "zoom": true,
      "search": false
    }
  },
  {
    "id": "adobe-palette-design",
    "label": "Adobe Color Palettes",
    "category": "asset",
    "extensions": [
      "ase",
      "aco"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "ASE 1.x",
      "ACO v1/v2"
    ],
    "knownLimits": [
      "ASE RGB, CMYK, Gray, and CIELAB colors and ACO RGB, HSB, CMYK, CIELAB, and Gray colors are parsed with strict bounds in a terminable module Worker",
      "Browser swatches convert CIELAB D50 and device CMYK to approximate sRGB; original model values remain visible for reference",
      "Unknown ASE blocks and bounded ACO trailing application data are skipped and reported rather than executed"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "photoshop-resource-design",
    "label": "Adobe Photoshop Resources and Presets",
    "category": "asset",
    "extensions": [
      "abr",
      "csh",
      "pat",
      "grd",
      "asl"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-design",
    "presets": [],
    "containerVersions": [
      "Photoshop ABR 6.x",
      "Photoshop CSH v2",
      "PAT v1",
      "GRD v5",
      "ASL v2",
      "ag-psd 31.0.2"
    ],
    "knownLimits": [
      "ABR previews decode saved brush-tip alpha, embedded patterns, and bounded preset metadata; they do not simulate Photoshop's stroke engine, dynamics, or paint blending",
      "CSH previews reconstruct bounded Bezier path geometry; subtract, intersect, and exclude composition is exposed as metadata rather than claimed as Photoshop-equivalent raster output",
      "PAT previews decode bounded RGB, grayscale, indexed-color, alpha, Raw, and PackBits pattern tiles; unsupported image modes and compression variants fail closed",
      "GRD previews render saved solid color stops and deterministic bounded noise samples from v5 descriptors; they do not claim Photoshop's complete interpolation and color-management pipeline",
      "ASL previews expose bounded layer-effect descriptors, blend metadata, and embedded pattern thumbnails as a structure view; they do not rasterize Photoshop's full effect stack",
      "Legacy ABR variants before 6.x and unknown CSH container versions are rejected instead of being scanned heuristically"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": false,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "data-asset",
    "label": "Data Asset",
    "category": "asset",
    "extensions": [
      "ttf",
      "otf",
      "woff",
      "woff2",
      "psd",
      "ai",
      "eps",
      "sqlite",
      "wasm",
      "parquet",
      "avro",
      "webarchive"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-data",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Font",
      "design",
      "database",
      "binary data"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "binary-inspector",
    "label": "Binary Inspector",
    "category": "asset",
    "extensions": [
      "bin",
      "hex",
      "elf",
      "exe",
      "dll",
      "class",
      "macho"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-binary",
    "presets": [],
    "containerVersions": [
      "Raw bytes",
      "ELF",
      "PE/COFF",
      "Mach-O",
      "PNG",
      "ZIP",
      "WebAssembly",
      "Java class"
    ],
    "knownLimits": [
      "The package is explicit opt-in and never claims application/octet-stream or extensions owned by dedicated renderers",
      "Only a reviewed built-in template catalog is parsed in a terminable module Worker; user-authored templates, dynamic imports, editing, and patching are out of scope",
      "Whole inputs, parse time, structure nodes, nesting, and decoded string bytes are capped before data reaches the DOM; large files are rejected instead of partially scanning arbitrary pages"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  }
] as const satisfies readonly RendererDefinition[];

export const DEFAULT_REGISTERED_EXTENSIONS = Object.freeze(
  Array.from(new Set(DEFAULT_RENDERER_DEFINITIONS.flatMap(definition => definition.extensions))).sort()
);

export const DEFAULT_STABLE_SUPPORTED_EXTENSIONS = Object.freeze(
  Array.from(new Set(DEFAULT_RENDERER_DEFINITIONS
    .filter(definition => definition.status === 'stable')
    .flatMap(definition => definition.extensions))).sort()
);

/** @deprecated Use DEFAULT_REGISTERED_EXTENSIONS when the experimental/stable distinction matters. */
export const DEFAULT_SUPPORTED_EXTENSIONS = DEFAULT_REGISTERED_EXTENSIONS;
