/* This file is generated by scripts/generate-format-catalog.mjs. Do not edit directly. */
export const FORMAT_CATALOG_SUMMARY = {
  "rendererCount": 48,
  "registeredExtensionCount": 275,
  "stableExtensionCount": 224,
  "experimentalExtensionCount": 51
} as const

export const OFFICE_FORMAT_GROUPS = [
  {
    "id": "office-word-openxml",
    "label": "Word OpenXML",
    "extensions": [
      "docx",
      "docm",
      "dotx",
      "dotm"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": [
      "VBA is never executed"
    ]
  },
  {
    "id": "office-word-binary",
    "label": "Word Binary",
    "extensions": [
      "doc",
      "dot"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "Macros are never executed"
    ]
  },
  {
    "id": "office-presentation-binary",
    "label": "PowerPoint 97–2003",
    "extensions": [
      "ppt",
      "pot"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "Embedded engine watermark is retained",
      "Macros are never executed"
    ]
  },
  {
    "id": "office-presentation",
    "label": "PowerPoint OpenXML",
    "extensions": [
      "pptx",
      "pptm",
      "potx",
      "potm",
      "ppsx",
      "ppsm"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": [
      "Macros and external programs are never executed"
    ]
  },
  {
    "id": "open-document",
    "label": "Open Document",
    "extensions": [
      "rtf",
      "odt",
      "odp"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": []
  },
  {
    "id": "spreadsheet-openxml",
    "label": "Spreadsheet",
    "extensions": [
      "xlsx",
      "xltx",
      "xlsm",
      "xlsb",
      "xls",
      "xlt",
      "xla",
      "xlam",
      "xltm",
      "csv",
      "tsv",
      "ods",
      "fods"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "VBA and add-in code are never executed",
      "Formula results are read from the saved workbook cache"
    ]
  },
  {
    "id": "apple-pages",
    "label": "Apple Pages",
    "extensions": [
      "pages"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": [
      "Static preview only",
      "Encrypted iwpv2 files are detected but not decrypted"
    ]
  },
  {
    "id": "apple-numbers",
    "label": "Apple Numbers",
    "extensions": [
      "numbers"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": [
      "Formula results are read from the saved document cache",
      "Encrypted iwpv2 files are detected but not decrypted"
    ]
  },
  {
    "id": "apple-keynote",
    "label": "Apple Keynote",
    "extensions": [
      "key"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": [
      "Animations, transitions and video playback are not executed",
      "Encrypted iwpv2 files are detected but not decrypted"
    ]
  },
  {
    "id": "office-wordperfect",
    "label": "WordPerfect",
    "extensions": [
      "wpd",
      "wp",
      "wp5",
      "wp6"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "Macros are never executed",
      ".wp5 and .wp6 are routing aliases for genuine WP5/WP6 payloads, not separate container formats",
      "Pagination and unsupported embedded objects are presented as structured static preview"
    ]
  },
  {
    "id": "spreadsheet-dbf",
    "label": "dBASE Table",
    "extensions": [
      "dbf"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "Missing DBT/FPT memo sidecars are reported as incomplete"
    ]
  },
  {
    "id": "pdf",
    "label": "PDF",
    "extensions": [
      "pdf"
    ],
    "supportLevel": "high-fidelity",
    "status": "stable",
    "knownLimits": []
  },
  {
    "id": "ofd",
    "label": "OFD",
    "extensions": [
      "ofd"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": []
  },
  {
    "id": "office-hangul",
    "label": "Hancom Hangul",
    "extensions": [
      "hwp",
      "hwpx"
    ],
    "supportLevel": "structured",
    "status": "stable",
    "knownLimits": [
      "Encrypted, DRM-protected and distribution documents are detected but not decrypted",
      "Charts, OLE objects and advanced drawing effects remain limited in the static structured preview",
      "HWP v5 pagination is approximated when the binary producer omits usable page geometry"
    ]
  }
] as const
